FROM python:3.12-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Set the working directory
WORKDIR /app

COPY pyproject.toml .
COPY uv.lock .
COPY .python-version .
COPY Makefile .
COPY agent ./agent

# Install the dependencies
RUN uv sync

ENV PATH="/app/.venv/bin:$PATH"

CMD ["uvicorn", "agent.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
# Expose the port
EXPOSE 80